# Generated by Django 4.2.4 on 2023-08-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_faceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='faceid',
            field=models.CharField(max_length=500000),
        ),
    ]
