# Generated by Django 4.2.4 on 2023-08-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_faceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='faceid',
            new_name='image',
        ),
    ]
