# Generated by Django 4.2.4 on 2023-08-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_faceid_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avalcash',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='investedcash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
