# Generated by Django 4.2.4 on 2023-08-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STOCK',
        ),
    ]
