# Generated by Django 4.2.4 on 2023-08-10 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='STOCK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockcode', models.CharField(max_length=100)),
                ('stockname', models.CharField(max_length=200)),
                ('ltp', models.IntegerField(default=1)),
                ('quant', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
